on:
  pull_requests:
  push:
    branches:
      - master

strategy:
  matrix:
    node: [8, 10, 12]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run unit tests
        run: npm run test



